CREATE TABLE students_grading (
    student_id VARCHAR(10) PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(255) UNIQUE,
    gender VARCHAR(10),
    age INT,
    department VARCHAR(100),
    attendance_percentage FLOAT,
    midterm_score FLOAT,
    final_score FLOAT,
    assignments_avg FLOAT,
    quizzes_avg FLOAT,
    participation_score FLOAT,
    projects_score FLOAT,
    total_score FLOAT,
    grade CHAR(1),
    study_hours_per_week FLOAT,
    extracurricular_activities VARCHAR(5),
    internet_access_at_home VARCHAR(5),
    parent_education_level VARCHAR(50),
    family_income_level VARCHAR(20),
    stress_level INT,
    sleep_hours_per_night FLOAT,
    sleep_category VARCHAR(20)
);
